version: '3'

services:

  sagi-web-0.0.2:
    build:
      context: .
    container_name: sagi-web
    tty: true
    ports:
      - "8080:80"
    volumes:
      - "/app/node_modules"
      - ".:/app"
